export const C = {
  dark: "#2C2C2A",
  mid: "#4A4846",
  accent: "#5F5E5A",
  lightBg: "#F1EFE8",
  border: "#D3D1C7",
  white: "#ffffff",
  gold: "#BA7517",
  goldLight: "#FAEEDA",
};

export const S = {
  page: {
    fontFamily: "'Georgia', serif",
    background: C.lightBg,
    minHeight: "100vh",
    color: C.dark,
  },
  navbar: {
    background: C.white,
    borderBottom: `1px solid ${C.border}`,
    padding: "0 2rem",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    height: "64px",
    position: "sticky",
    top: 0,
    zIndex: 10,
  },
  brand: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    fontWeight: "700",
    fontSize: "15px",
    color: C.dark,
    textDecoration: "none",
    letterSpacing: "0.5px",
  },
  logoCircle: {
    width: "38px",
    height: "38px",
    borderRadius: "50%",
    background: C.dark,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: C.white,
    fontSize: "13px",
    fontWeight: "700",
    flexShrink: 0,
  },
  navLinks: {
    display: "flex",
    gap: "2rem",
    listStyle: "none",
    margin: 0,
    padding: 0,
  },
  navLink: {
    color: C.accent,
    textDecoration: "none",
    fontSize: "14px",
    fontFamily: "sans-serif",
  },
  navLinkActive: {
    color: C.dark,
    fontWeight: "600",
    borderBottom: `2px solid ${C.gold}`,
    paddingBottom: "2px",
  },
  hero: {
    background: C.dark,
    color: C.white,
    textAlign: "center",
    padding: "4rem 2rem 3rem",
  },
  heroLabel: {
    fontSize: "11px",
    letterSpacing: "3px",
    textTransform: "uppercase",
    color: C.gold,
    marginBottom: "0.75rem",
    fontFamily: "sans-serif",
  },
  heroTitle: {
    fontSize: "36px",
    fontWeight: "700",
    margin: "0 0 0.75rem",
    letterSpacing: "1px",
  },
  heroSub: {
    color: "#B4B2A9",
    fontSize: "15px",
    maxWidth: "520px",
    margin: "0 auto",
    lineHeight: "1.8",
    fontFamily: "sans-serif",
  },
  card: {
    background: C.white,
    border: `0.5px solid ${C.border}`,
    borderRadius: "12px",
    padding: "1.75rem",
  },
  cardTitle: {
    fontSize: "13px",
    fontWeight: "600",
    letterSpacing: "2px",
    textTransform: "uppercase",
    color: C.gold,
    marginBottom: "1.25rem",
    fontFamily: "sans-serif",
  },
  footer: {
    background: C.dark,
    color: "#B4B2A9",
    textAlign: "center",
    padding: "1.5rem",
    fontSize: "13px",
    fontFamily: "sans-serif",
    marginTop: "2rem",
  },
};